// Single source of truth for all player data.
// Format: [id, name, category, era, wiki_slug_or_null, bio, handles, scoring, quickness, heart, court_iq]
// Run `npm run build-players` to regenerate seed-players.json with Wikipedia images.

// ─── NBA ──────────────────────────────────────────────────────────────────────
export const NBA = [
  // ALL-TIME LEGENDS
  ["magic",     "Magic Johnson",          "NBA", "All-Time", "Magic_Johnson",                       "Showtime PG. 5 rings. Greatest floor general ever.",            99,90,88,95,99],
  ["bird",      "Larry Bird",             "NBA", "All-Time", "Larry_Bird",                          "Cold-blooded. Talked trash, then backed every word.",            92,97,78,99,99],
  ["kareem",    "Kareem Abdul-Jabbar",    "NBA", "All-Time", "Kareem_Abdul-Jabbar",                 "6 rings. Skyhook is unblockable. Science agrees.",              75,98,75,88,96],
  ["oscar",     "Oscar Robertson",        "NBA", "All-Time", "Oscar_Robertson",                     "Triple-double every night before it was even tracked.",          95,90,85,92,98],
  ["jerrywest", "Jerry West",             "NBA", "All-Time", "Jerry_West",                          "Mr. Clutch. The logo. 30 PPG in the playoffs.",                 90,95,90,98,95],
  ["drj",       "Julius Erving",          "NBA", "All-Time", "Julius_Erving",                       "Dr. J invented the blueprint for every wing that followed.",     92,93,94,95,92],
  ["wilt",      "Wilt Chamberlain",       "NBA", "All-Time", "Wilt_Chamberlain",                    "100-point game. 50 PPG season. Math doesn't lie.",               65,99,80,88,85],
  ["russell",   "Bill Russell",           "NBA", "All-Time", "Bill_Russell_(basketball)",           "11 rings. Won't ever happen again.",                            60,75,82,99,97],
  ["baylor",    "Elgin Baylor",           "NBA", "All-Time", "Elgin_Baylor",                        "Jordan and Dr. J both studied him. The original.",               88,95,90,92,90],
  ["pistol",    "Pete Maravich",          "NBA", "All-Time", "Pete_Maravich",                       "Pistol Pete. Handle 50 years ahead of its time.",               99,97,88,88,95],
  ["frazier",   "Walt Frazier",           "NBA", "All-Time", "Walt_Frazier",                        "Clyde. Style, lockdown D, and 20 a night in MSG.",              88,85,88,88,92],
  ["cousy",     "Bob Cousy",              "NBA", "All-Time", "Bob_Cousy",                           "First great floor general. 6 championships with Russell.",       93,78,88,85,97],

  // 90s
  ["mj",        "Michael Jordan",         "NBA", "90s",      "Michael_Jordan",                      "GOAT. 6 rings. Never lost in the Finals. Period.",              92,99,95,100,98],
  ["pippen",    "Scottie Pippen",         "NBA", "90s",      "Scottie_Pippen",                      "Top 5 defender ever. Jordan needed him and knew it.",           88,85,93,90,94],
  ["barkley",   "Charles Barkley",        "NBA", "90s",      "Charles_Barkley",                     "Round Mound of Rebound. Nobody outworked him.",                 78,94,85,97,90],
  ["ewing",     "Patrick Ewing",          "NBA", "90s",      "Patrick_Ewing",                       "NY royalty. Post game was automatic.",                          72,92,78,92,88],
  ["hakeem",    "Hakeem Olajuwon",        "NBA", "90s",      "Hakeem_Olajuwon",                     "Dream Shake. Most skilled big man to ever lace em up.",         78,93,85,93,97],
  ["admiral",   "David Robinson",         "NBA", "90s",      "David_Robinson_(basketball)",         "The Admiral. Navy discipline, unstoppable athletic peak.",       70,91,84,90,88],
  ["gp",        "Gary Payton",            "NBA", "90s",      "Gary_Payton",                         "The Glove. Talked everyone to death then locked them up.",       95,87,90,94,95],
  ["reggie",    "Reggie Miller",          "NBA", "90s",      "Reggie_Miller",                       "8 points in 8.9 seconds. Knicks killer. Pure ice.",             82,94,84,98,90],
  ["stockton",  "John Stockton",          "NBA", "90s",      "John_Stockton",                       "All-time assists and steals leader. Undersized. Unstoppable.",   97,82,86,90,99],
  ["malone",    "Karl Malone",            "NBA", "90s",      "Karl_Malone",                         "The Mailman. Delivered 36,928 points.",                         70,95,82,94,85],
  ["drexler",   "Clyde Drexler",          "NBA", "90s",      "Clyde_Drexler",                       "Clyde the Glide. Houston's answer to Jordan.",                  90,93,92,92,90],
  ["nique",     "Dominique Wilkins",      "NBA", "90s",      "Dominique_Wilkins",                   "Human Highlight Film. Dunk contest royalty.",                   82,97,90,94,85],
  ["shaq",      "Shaquille O'Neal",       "NBA", "2000s",    "Shaquille_O%27Neal",                  "Most dominant interior force in basketball history.",            58,98,72,90,82],
  ["penny",     "Penny Hardaway",         "NBA", "90s",      "Anfernee_Hardaway",                   "Magic's athleticism meets Jordan's handle. What could've been.", 93,90,91,88,92],
  ["kemp",      "Shawn Kemp",             "NBA", "90s",      "Shawn_Kemp",                          "Reign Man. Posterized everything that moved.",                  72,90,90,92,80],
  ["granthill", "Grant Hill",             "NBA", "90s",      "Grant_Hill_(basketball)",             "Before the ankle. Would've been top 10 all time.",              88,90,91,90,91],
  ["rodman",    "Dennis Rodman",          "NBA", "90s",      "Dennis_Rodman",                       "Rebounding and chaos. Irreplaceable weird genius.",             60,65,85,99,85],
  ["timhardaway","Tim Hardaway",          "NBA", "90s",      "Tim_Hardaway",                        "UTEP Two-Step. The crossover before it had a name.",            96,88,90,88,88],
  ["zo",        "Alonzo Mourning",        "NBA", "90s",      "Alonzo_Mourning",                     "Zo blocked shots with bad intentions.",                         62,88,80,95,85],
  ["isiah",     "Isiah Thomas",           "NBA", "90s",      "Isiah_Thomas",                        "Bad Boy general. Dropped 25 on one leg in the Finals.",         96,90,95,99,95],

  // 2000s
  ["ai",        "Allen Iverson",          "NBA", "2000s",    "Allen_Iverson",                       "The Answer. 6 feet of pure heart and crossover.",               99,95,99,100,88],
  ["kobe",      "Kobe Bryant",            "NBA", "2000s",    "Kobe_Bryant",                         "Mamba Mentality. 5 rings. 81 points. No explanation needed.",    92,99,92,100,96],
  ["tmac",      "Tracy McGrady",          "NBA", "2000s",    "Tracy_McGrady",                       "13 points in 35 seconds. Could not be stopped.",                90,97,91,88,90],
  ["dwade",     "Dwyane Wade",            "NBA", "2000s",    "Dwyane_Wade",                         "Flash. Finals MVP at 23. Made impossible look routine.",         90,93,96,95,92],
  ["pierce",    "Paul Pierce",            "NBA", "2000s",    "Paul_Pierce",                         "The Truth. Cold-blooded shot-maker. Ring in Boston.",            88,93,82,94,92],
  ["kg",        "Kevin Garnett",          "NBA", "2000s",    "Kevin_Garnett",                       "KG. Intensity that changed the temperature of every gym.",       80,92,87,99,94],
  ["timmy",     "Tim Duncan",             "NBA", "2000s",    "Tim_Duncan",                          "The Big Fundamental. 5 rings. Boring means dominant.",          72,92,78,92,97],
  ["nash",      "Steve Nash",             "NBA", "2000s",    "Steve_Nash",                          "Back-to-back MVP. SSOL Phoenix was basketball on fast-forward.", 97,87,85,90,99],
  ["vc",        "Vince Carter",           "NBA", "2000s",    "Vince_Carter",                        "Half Man Half Amazing. Best dunker ever. Period.",               87,93,92,85,85],
  ["rayallen",  "Ray Allen",              "NBA", "2000s",    "Ray_Allen",                           "Corner three. Corner three. Corner three. Hall of Fame.",        85,93,87,92,90],
  ["melo",      "Carmelo Anthony",        "NBA", "2000s",    "Carmelo_Anthony",                     "Pure scorer. Top 15 all time. The iso god.",                    85,97,85,90,88],
  ["dirk",      "Dirk Nowitzki",          "NBA", "2000s",    "Dirk_Nowitzki",                       "One-legged fadeaway that nobody could contest. Legend.",         80,97,75,94,95],
  ["kidd",      "Jason Kidd",             "NBA", "2000s",    "Jason_Kidd",                          "Triple-double machine. Maestro. Needed no handle.",             95,80,88,88,97],
  ["amare",     "Amar'e Stoudemire",      "NBA", "2000s",    "Amar%27e_Stoudemire",                 "Alley-oop terminus. SUNS SUNS SUNS.",                           68,92,88,90,80],
  ["arenas",    "Gilbert Arenas",         "NBA", "2000s",    "Gilbert_Arenas",                      "Agent Zero. Top 5 most unguardable in his prime.",              90,95,88,92,87],
  ["bd",        "Baron Davis",            "NBA", "2000s",    "Baron_Davis",                         "God Shammgod Jr. Killed Dallas in 2007. Still iconic.",          93,90,92,92,88],
  ["billups",   "Chauncey Billups",       "NBA", "2000s",    "Chauncey_Billups",                    "Mr. Big Shot. Made every one that counted.",                    90,88,82,95,94],
  ["tp",        "Tony Parker",            "NBA", "2000s",    "Tony_Parker",                         "Bank shot through traffic. 4 rings. Fastest in the key.",       90,88,94,90,92],
  ["manu",      "Manu Ginobili",          "NBA", "2000s",    "Manu_Ginobili",                       "Euro step inventor. Left hand scalpel. Chaos in a uniform.",    88,90,88,96,93],
  ["yao",       "Yao Ming",               "NBA", "2000s",    "Yao_Ming",                            "7'6 with touch and IQ. What could have been.",                  65,90,65,88,88],
  ["bosh",      "Chris Bosh",             "NBA", "2000s",    "Chris_Bosh",                          "Stretch 4 before it was a position. Two rings in Miami.",        72,88,82,85,85],
  ["marbury",   "Stephon Marbury",        "NBA", "2000s",    "Stephon_Marbury",                     "Starbury. China's king. Should have had his moment.",            94,90,92,82,85],
  ["bwallace",  "Ben Wallace",            "NBA", "2000s",    "Ben_Wallace_(basketball)",            "Undrafted. 4x Defensive Player of the Year.",                   55,65,82,97,85],
  ["lamar",     "Lamar Odom",             "NBA", "2000s",    "Lamar_Odom",                          "6th Man MVP. Could do everything at 6'10.",                     85,85,84,82,88],
  ["lbj",       "LeBron James",           "NBA", "Current",  "LeBron_James",                        "The King. Freight train with point guard vision.",              90,96,90,92,99],
  ["kd",        "Kevin Durant",           "NBA", "Current",  "Kevin_Durant",                        "Easy Money Sniper. Unguardable jumper at 7 feet.",              88,99,88,92,95],
  ["kyrie",     "Kyrie Irving",           "NBA", "Current",  "Kyrie_Irving",                        "Best handles to ever do it. Game 7 dagger.",                    100,95,96,90,92],

  // 2010s
  ["russ",      "Russell Westbrook",      "NBA", "2010s",    "Russell_Westbrook",                   "Triple-double machine. Pure will and athleticism.",             90,94,98,99,85],
  ["harden",    "James Harden",           "NBA", "2010s",    "James_Harden",                        "Step back king. Engineered his own rules.",                     95,98,85,88,93],
  ["ad",        "Anthony Davis",          "NBA", "2010s",    "Anthony_Davis_(basketball)",          "The Brow. Unstoppable when his mind is right.",                 75,94,88,88,90],
  ["drose",     "Derrick Rose",           "NBA", "2010s",    "Derrick_Rose",                        "Youngest MVP ever. 2011 Rose was flat out unguardable.",         92,92,99,96,88],
  ["dwight",    "Dwight Howard",          "NBA", "2010s",    "Dwight_Howard",                       "Prime Dwight was a cheat code in the paint.",                   55,88,85,88,75],
  ["blake",     "Blake Griffin",          "NBA", "2010s",    "Blake_Griffin",                       "Lob City legend. Poster machine. Best power forward highlight reel.", 80,92,90,90,85],
  ["klay",      "Klay Thompson",          "NBA", "2010s",    "Klay_Thompson",                       "11 dribbles to the championship. No dribbles needed.",          82,95,88,90,88],
  ["pg13",      "Paul George",            "NBA", "2010s",    "Paul_George",                         "PG-13. Lockdown wing and elite scorer in his prime.",            84,90,89,88,88],
  ["jwall",     "John Wall",              "NBA", "2010s",    "John_Wall",                           "Fastest in the league when healthy. Explosive.",                94,88,98,90,88],
  ["kawhi",     "Kawhi Leonard",          "NBA", "2010s",    "Kawhi_Leonard",                       "The Klaw. Bounce. Bounce. Bounce. Swish. 2019 magic.",           85,94,88,94,94],
  ["dray",      "Draymond Green",         "NBA", "2010s",    "Draymond_Green",                      "4 rings. Most impactful player of his era. Not flashy.",         80,72,82,97,98],
  ["kat",       "Karl-Anthony Towns",     "NBA", "2010s",    "Karl-Anthony_Towns",                  "KAT. Most skilled offensive big since Dirk.",                   75,92,78,82,87],
  ["cp3",       "Chris Paul",             "NBA", "2010s",    "Chris_Paul",                          "Point God. IQ through the roof. Career-long dominance.",         97,88,88,90,99],
  ["rondo",     "Rajon Rondo",            "NBA", "2010s",    "Rajon_Rondo",                         "Chess genius on the court. Playoff Rondo was something else.",   97,72,85,88,97],
  ["derozan",   "DeMar DeRozan",          "NBA", "2010s",    "DeMar_DeRozan",                       "Lambo. Mid-range artist. Bank shot is the whole menu.",         86,92,82,92,88],
  ["kemba",     "Kemba Walker",           "NBA", "2010s",    "Kemba_Walker",                        "Queen City legend. Buckets in no space at all.",                91,90,90,90,87],
  ["beal",      "Bradley Beal",           "NBA", "2010s",    "Bradley_Beal",                        "Consistent scorer. Could always get a bucket.",                 86,92,86,88,87],
  ["it4",       "Isaiah Thomas",          "NBA", "2010s",    "Isaiah_Thomas_(basketball)",          "5'9 and averaging 29. Heart bigger than his stature.",          93,94,88,98,88],
  ["lamelo",    "LaMelo Ball",            "NBA", "Current",  "LaMelo_Ball",                         "Melo. Passes nobody sees coming. Born for this.",               96,86,86,82,93],

  // CURRENT
  ["curry",     "Stephen Curry",          "NBA", "Current",  "Stephen_Curry",                       "Greatest shooter ever. Changed the whole game forever.",         99,97,90,92,99],
  ["giannis",   "Giannis Antetokounmpo", "NBA", "Current",  "Giannis_Antetokounmpo",               "Greek Freak. From Athens to MVP to ring. No ceiling.",           85,96,95,96,90],
  ["jokic",     "Nikola Jokic",           "NBA", "Current",  "Nikola_Joki%C4%87",                   "Joker. 3x MVP. Plays chess while everyone plays checkers.",      82,94,72,88,99],
  ["embiid",    "Joel Embiid",            "NBA", "Current",  "Joel_Embiid",                         "The Process delivered. Unstoppable when healthy.",              76,95,78,90,92],
  ["luka",      "Luka Doncic",            "NBA", "Current",  "Luka_Don%C4%8Di%C4%87",               "Luka magic. EuroStep into legend status.",                      95,97,82,90,98],
  ["jtatum",    "Jayson Tatum",           "NBA", "Current",  "Jayson_Tatum",                        "Banner 18. Star in Celtics green.",                             87,94,87,90,90],
  ["trae",      "Trae Young",             "NBA", "Current",  "Trae_Young",                          "Ice Trae. Half-court range. Madison Square villain.",            97,94,85,86,95],
  ["zion",      "Zion Williamson",        "NBA", "Current",  "Zion_Williamson",                     "280 lbs at 6'6. Defies every law of physics.",                  82,94,94,90,84],
  ["ja",        "Ja Morant",              "NBA", "Current",  "Ja_Morant",                           "Straight up. Most explosive in the league.",                    93,92,99,94,87],
  ["dbook",     "Devin Booker",           "NBA", "Current",  "Devin_Booker",                        "Book. Cold-blooded scorer. Kobe studied him before he was born.", 88,95,87,92,90],
  ["ant",       "Anthony Edwards",        "NBA", "Current",  "Anthony_Edwards_(basketball)",        "Ant-Man. The face of the next NBA era.",                        88,93,95,93,86],
  ["sga",       "Shai Gilgeous-Alexander","NBA", "Current",  "Shai_Gilgeous-Alexander",             "SGA. Slowest-looking fast player in the league.",               93,96,90,90,93],
  ["dmitch",    "Donovan Mitchell",       "NBA", "Current",  "Donovan_Mitchell_(basketball)",       "Spida. Clutch gene runs deep.",                                 88,93,90,92,88],
  ["jbrown",    "Jaylen Brown",           "NBA", "Current",  "Jaylen_Brown",                        "JB. Co-star to Finals MVP. Earned every bit of it.",            84,90,92,90,84],
  ["bam",       "Bam Adebayo",            "NBA", "Current",  "Bam_Adebayo",                         "Best defensive anchor of his generation.",                      78,86,84,90,90],
  ["wemby",     "Victor Wembanyama",      "NBA", "Current",  "Victor_Wembanyama",                   "Alien. 7'4 wingspan with guard skills. New category.",           80,92,85,86,90],
  ["paolo",     "Paolo Banchero",         "NBA", "Current",  "Paolo_Banchero",                      "Duke to Magic. Next face of the franchise.",                    82,90,82,86,86],
  ["dame",      "Damian Lillard",         "NBA", "Current",  "Damian_Lillard",                      "Dame Time. 40-foot daggers as a lifestyle choice.",             93,95,87,95,91],
  ["sga2",      "SGA 2024",               "NBA", "Current",  "Shai_Gilgeous-Alexander",             "2024 scoring champ mode. Literally unguardable.",               95,98,91,92,94],
  ["tyhal",     "Tyrese Haliburton",      "NBA", "Current",  "Tyrese_Haliburton",                   "Hali. Basketball IQ in the 99th percentile.",                   91,86,86,86,94],
  ["dafox",     "De'Aaron Fox",           "NBA", "Current",  "De%27Aaron_Fox",                      "Chasing a championship at mach speed.",                         91,88,97,88,86],
  ["brunson",   "Jalen Brunson",          "NBA", "Current",  "Jalen_Brunson",                       "Madison Square Garden's franchise. Won't be denied.",           88,90,82,92,90],
  ["cade",      "Cade Cunningham",        "NBA", "Current",  "Cade_Cunningham",                     "Pistons franchise piece. Methodical and dangerous.",            90,88,84,86,90],
];

// ─── WNBA ─────────────────────────────────────────────────────────────────────
export const WNBA = [
  // 90s (early WNBA, founded 1997)
  ["lisa-leslie", "Lisa Leslie", "WNBA", "90s", "Lisa_Leslie", "First to dunk in a WNBA game. 3x MVP. Legend.", 82, 92, 80, 95, 90],
  ["sheryl-swoopes", "Sheryl Swoopes", "WNBA", "90s", "Sheryl_Swoopes", "3x MVP, 3x DPOY. The Michael Jordan of the WNBA.", 90, 94, 92, 95, 92],
  ["cynthia-cooper", "Cynthia Cooper", "WNBA", "90s", "Cynthia_Cooper-Dyke", "4 straight titles with the Comets. Clutch personified.", 92, 95, 88, 98, 94],
  ["rebecca-lobo", "Rebecca Lobo", "WNBA", "90s", "Rebecca_Lobo", "UConn legend. Changed women's basketball forever.", 78, 82, 72, 88, 86],
  ["teresa-weatherspoon", "Teresa Weatherspoon", "WNBA", "90s", "Teresa_Weatherspoon", "The Shot. NY Liberty icon. Floor general.", 94, 82, 90, 95, 96],
  ["dawn-staley", "Dawn Staley", "WNBA", "90s", "Dawn_Staley", "Hall of Fame PG. Champion coach. Leader.", 95, 84, 88, 96, 98],

  // 2000s
  ["sue-bird", "Sue Bird", "WNBA", "2000s", "Sue_Bird", "4x champ. All-time assists leader. Seattle royalty.", 96, 86, 84, 92, 99],
  ["diana-taurasi", "Diana Taurasi", "WNBA", "2000s", "Diana_Taurasi", "GOAT scorer. All-time leading scorer. Killer instinct.", 90, 99, 86, 96, 94],
  ["tamika-catchings", "Tamika Catchings", "WNBA", "2000s", "Tamika_Catchings", "10x All-Star, MVP, DPOY, champion. Complete player.", 86, 90, 90, 98, 94],
  ["lauren-jackson", "Lauren Jackson", "WNBA", "2000s", "Lauren_Jackson_(basketball)", "3x MVP. Australian legend. Most skilled big ever.", 82, 94, 84, 92, 90],
  ["yolanda-griffith", "Yolanda Griffith", "WNBA", "2000s", "Yolanda_Griffith", "MVP and champion. Dominant two-way force.", 78, 88, 82, 92, 86],
  ["katie-smith", "Katie Smith", "WNBA", "2000s", "Katie_Smith", "First woman to score 6,000 points. Pure bucket.", 84, 94, 82, 90, 88],
  ["tina-thompson", "Tina Thompson", "WNBA", "2000s", "Tina_Thompson", "4x champ. First draft pick in WNBA history.", 80, 92, 78, 90, 86],
  ["swin-cash", "Swin Cash", "WNBA", "2000s", "Swin_Cash", "3x champ. Leader. Clutch performer.", 84, 88, 86, 94, 88],
  ["chamique-holdsclaw", "Chamique Holdsclaw", "WNBA", "2000s", "Chamique_Holdsclaw", "6x All-Star. Tennessee legend. Could do it all.", 88, 92, 88, 88, 90],

  // 2010s
  ["candace-parker", "Candace Parker", "WNBA", "2010s", "Candace_Parker", "Only player with MVP and Rookie of Year same season.", 88, 92, 88, 92, 94],
  ["sylvia-fowles", "Sylvia Fowles", "WNBA", "2010s", "Sylvia_Fowles", "2x MVP, DPOY, 2x champ. Dominant center.", 72, 88, 78, 94, 86],
  ["maya-moore", "Maya Moore", "WNBA", "2010s", "Maya_Moore", "4x champ, MVP, Finals MVP. Winner in every sense.", 90, 96, 90, 98, 94],
  ["brittney-griner", "Brittney Griner", "WNBA", "2010s", "Brittney_Griner", "2x DPOY. 8x All-Star. Unstoppable in the post.", 76, 90, 76, 92, 84],
  ["elena-delle-donne", "Elena Delle Donne", "WNBA", "2010s", "Elena_Delle_Donne", "2x MVP. Most efficient scorer in WNBA history.", 86, 98, 84, 92, 92],
  ["nneka-ogwumike", "Nneka Ogwumike", "WNBA", "2010s", "Nneka_Ogwumike", "MVP, champion. Stanford to WNBA royalty.", 84, 92, 88, 94, 90],
  ["angel-mccoughtry", "Angel McCoughtry", "WNBA", "2010s", "Angel_McCoughtry", "5x All-Star. Scoring machine. Atlanta legend.", 88, 94, 92, 92, 88],
  ["lindsay-whalen", "Lindsay Whalen", "WNBA", "2010s", "Lindsay_Whalen", "4x champ. Minnesota legend. Clutch point guard.", 92, 86, 86, 94, 94],
  ["seimone-augustus", "Seimone Augustus", "WNBA", "2010s", "Seimone_Augustus", "4x champ. Smooth scorer. LSU legend.", 88, 94, 86, 90, 88],
  ["tina-charles", "Tina Charles", "WNBA", "2010s", "Tina_Charles_(basketball)", "2010 Rookie of Year, MVP. Double-double machine.", 78, 92, 80, 92, 86],

  // Current
  ["aja-wilson", "A'ja Wilson", "WNBA", "Current", "A%27ja_Wilson", "3x MVP, 2x DPOY, 2x champ. Most dominant force today.", 78, 96, 84, 96, 90],
  ["breanna-stewart", "Breanna Stewart", "WNBA", "Current", "Breanna_Stewart", "2x MVP, 2x champ. Freakish skill at 6'4.", 86, 94, 88, 94, 92],
  ["sabrina-ionescu", "Sabrina Ionescu", "WNBA", "Current", "Sabrina_Ionescu", "Triple-double queen. First overall pick. Franchise.", 94, 90, 88, 92, 96],
  ["caitlin-clark", "Caitlin Clark", "WNBA", "Current", "Caitlin_Clark", "Rookie of Year. Logo threes. Changed the game.", 96, 94, 88, 92, 94],
  ["angel-reese", "Angel Reese", "WNBA", "Current", "Angel_Reese", "Rookie. LSU champion. Double-double machine.", 78, 86, 82, 94, 84],
  ["aliyah-boston", "Aliyah Boston", "WNBA", "Current", "Aliyah_Boston", "Rookie of Year. South Carolina legend. Skilled big.", 76, 88, 78, 92, 88],
  ["kelsey-plum", "Kelsey Plum", "WNBA", "Current", "Kelsey_Plum", "All-time NCAA scorer. 3x champ. Bucket getter.", 90, 92, 86, 90, 90],
  ["chelsea-gray", "Chelsea Gray", "WNBA", "Current", "Chelsea_Gray", "3x champ. Best point guard in the game right now.", 96, 90, 88, 92, 98],
  ["jewell-loyd", "Jewell Loyd", "WNBA", "Current", "Jewell_Loyd", "2x champ. Gold Mamba. Elite scorer.", 90, 94, 92, 92, 90],
  ["arike-ogunbowale", "Arike Ogunbowale", "WNBA", "Current", "Arike_Ogunbowale", "Clutch gene. Notre Dame legend. Daggers only.", 92, 94, 92, 96, 90],
];

// ─── STREETBALL ───────────────────────────────────────────────────────────────
export const STREETBALL = [
  ["skip",      "Skip 2 My Lou",          "Streetball Icons", "2000s", null, "AND1 floor general. Pope of the playground.",              100,88,95,95,92],
  ["hotsauce",  "Hot Sauce",              "Streetball Icons", "2000s", null, "Most disrespectful handle in history. Philip Champion.",   100,82,96,90,90],
  ["peewee",    "Pee Wee Kirkland",       "Streetball Icons", "90s",   null, "Rucker Park royalty. Turned down the NBA.",                95,95,90,95,94],
  ["jwill",     "White Chocolate",        "Streetball Icons", "2000s", "Jason_Williams_(basketball,_born_1975)", "Behind-the-back elbow pass. Sacramento magic.",  99,86,92,88,95],
  ["ao",        "AO",                     "Streetball Icons", "2010s", null, "The Crime Stopper. 5'7 scoring machine from Baltimore.",    97,96,99,92,88],
  ["bone",      "Bone Collector",         "Streetball Icons", "2000s", null, "Ankles get filed in his collection.",                      100,88,95,92,90],
  ["professor", "The Professor",          "Streetball Icons", "2000s", "Grayson_Boucher", "YouTube legend. Most watched handles on the planet.",     100,82,92,88,90],
  ["escalade",  "Escalade",               "Streetball Icons", "2000s", null, "AND1 enforcer. Could take it to the hole every time.",      82,90,88,90,82],
  ["main",      "Main Event",             "Streetball Icons", "2000s", null, "AND1's showman. Crowd went crazy every touch.",             88,85,88,92,85],
  ["airupthere","Air Up There",           "Streetball Icons", "2000s", null, "Waliyy Dixon. Floating, twisting, automatic.",              90,88,94,88,85],
  ["future",    "Future Shawn",           "Streetball Icons", "2000s", null, "AND1 circuit. Pure offense on the blacktop.",               88,88,88,85,82],
  ["hmha",      "Half Man Half Amazing",  "Streetball Icons", "2000s", null, "Justin Irvin. The name says everything.",                  88,85,94,88,82],
  ["disco",     "Disco Lando",            "Streetball Icons", "2000s", null, "Harlem's own. Entertainment plus buckets.",                 88,85,85,88,85],
  ["duke",      "Duke",                   "Streetball Icons", "2000s", null, "AND1's lockdown plus scorer. Complete game.",               84,85,88,90,85],
];

// ─── CELEBRITY BALLERS ────────────────────────────────────────────────────────
export const CELEBRITY = [
  ["hart",       "Kevin Hart",       "Celebrity Ballers", "Current", "Kevin_Hart",                          "Celebrity All-Star MVP. Real bucket for 5'2.",              78,80,88,95,80],
  ["quavo",      "Quavo",            "Celebrity Ballers", "Current", "Quavo",                               "Huncho Hoops. Actually nice.",                              82,84,84,88,82],
  ["drake",      "Drake",            "Celebrity Ballers", "Current", "Drake_(entertainer)",                 "Sideline GM. Form is suspect but he tries.",                70,72,70,80,80],
  ["uzi",        "Lil Uzi",          "Celebrity Ballers", "Current", "Lil_Uzi_Vert",                        "Quick first step. Splash from deep.",                       85,80,92,85,78],
  ["bieber",     "Justin Bieber",    "Celebrity Ballers", "Current", "Justin_Bieber",                       "Canadian baller. Underrated handle.",                       82,78,84,82,80],
  ["postmalone", "Post Malone",      "Celebrity Ballers", "Current", "Post_Malone",                         "6'2 of country trap energy.",                               70,74,68,88,76],
  ["druski",     "Druski",           "Celebrity Ballers", "Current", null,                                  "Coulda been a D1 walk-on. Pure theatre.",                   80,78,80,92,84],
  ["2chainz",    "2 Chainz",         "Celebrity Ballers", "Current", "2_Chainz",                            "6'5 former college player. Tity Boi buckets.",              78,82,78,88,78],
  ["jackharlow", "Jack Harlow",       "Celebrity Ballers", "Current", "Jack_Harlow",                        "Louisville's biggest rap-ball crossover.",                   80,78,80,85,80],
  ["meekmill",   "Meek Mill",        "Celebrity Ballers", "Current", "Meek_Mill",                           "Philly hooper at heart. Lives at Sixers games.",            78,76,80,90,76],
  ["common",     "Common",           "Celebrity Ballers", "Current", "Common_(rapper)",                     "Chicago raised. Respectful game. Been nice.",               76,74,78,85,78],
  ["masterp",    "Master P",         "Celebrity Ballers", "Current", "Master_P",                            "Actually signed a CBA contract. Hoodie Hoops.",             76,74,74,88,74],
  ["icecube",    "Ice Cube",         "Celebrity Ballers", "Current", "Ice_Cube",                            "Founded BIG3. Still talks the talk.",                       72,74,72,85,80],
  ["obama",      "Barack Obama",     "Celebrity Ballers", "Current", "Barack_Obama",                        "44th President. First ballot Celebrity HOF.",               75,74,76,88,82],
  ["mgk",        "Machine Gun Kelly","Celebrity Ballers", "Current", "Machine_Gun_Kelly_(musician)",        "Tall, scrappy, and tries too hard. Respect.",               72,72,76,80,72],
  ["wizkhalifa", "Wiz Khalifa",      "Celebrity Ballers", "Current", "Wiz_Khalifa",                         "Long arms, long range. Pittsburgh's rapper-baller.",        74,72,76,80,74],
  ["offset",     "Offset",           "Celebrity Ballers", "Current", "Offset_(rapper)",                     "Cardi's husband. Actually got game.",                       78,76,78,82,76],
  ["bowwow",     "Bow Wow",          "Celebrity Ballers", "Current", "Bow_Wow",                             "Claimed to hoop on Kobe. Shot himself in the foot.",        78,76,80,78,74],
  ["badbunny",   "Bad Bunny",        "Celebrity Ballers", "Current", "Bad_Bunny",                           "El Conejo. Puerto Rico's biggest star laces em up.",        72,72,72,82,72],
  ["theGame",    "The Game",         "Celebrity Ballers", "Current", "The_Game_(rapper)",                   "Compton's rapper-baller. Stocky with a shot.",              76,76,74,85,74],
  ["future",     "Future",           "Celebrity Ballers", "Current", "Future_(rapper)",                     "Pluto hoops. Says he's nice. Film is inconclusive.",        72,72,74,80,72],
  ["odell",      "Odell Beckham Jr", "Celebrity Ballers", "Current", "Odell_Beckham_Jr.",                   "NFL elite athlete. Crosses over like a guard.",             84,82,90,88,78],
];

// ─── FANTASY ──────────────────────────────────────────────────────────────────
export const FANTASY = [
  ["25-lbj",    "25-year-old LeBron",             "Fantasy", "All-Time", null, "Miami athletic peak. 2010. Locomotive with no brakes.", 90,95,95,92,97],
  ["25-mj",     "25-year-old Jordan",             "Fantasy", "All-Time", null, "1988 MJ. DPOY and scoring champ. Most athletic version.", 92,99,99,100,95],
  ["curry-no3", "Curry with no 3-point line",     "Fantasy", "All-Time", null, "Forced to live in the midrange. Still cooks everyone.", 99,94,90,92,99],
  ["prime-ai",  "Prime Iverson",                  "Fantasy", "2000s",    null, "2001 MVP. 48 minutes a night. No one stopped him.", 99,97,99,100,90],
  ["young-kobe","Young Kobe",                     "Fantasy", "2000s",    null, "2003 Kobe. Pre-rings. Hungriest version ever played.", 93,98,95,100,95],
  ["prime-kd",  "Prime KD",                       "Fantasy", "All-Time", null, "2014 MVP speech Kobe. 7 feet of pure scoring ability.", 88,99,88,95,95],
  ["young-shaq","Young Shaq",                     "Fantasy", "All-Time", null, "Orlando Shaq. Fastest and most explosive version.", 58,98,80,92,80],
  ["young-lebron","Young LeBron",                 "Fantasy", "All-Time", null, "2006 Cavaliers LeBron. When he was just raw and terrifying.", 92,94,98,94,95],
];
